#define INS_REV_DEF_allow_revive 0
#define INS_REV_DEF_respawn_delay 120
#define INS_REV_DEF_life_time -1
#define INS_REV_DEF_revive_take_time 15
#define INS_REV_DEF_require_medkit 0
#define INS_REV_DEF_respawn_type 0
#define INS_REV_DEF_respawn_location 0
#define INS_REV_DEF_displayRespawnLocationMarker 1
#define INS_REV_DEF_respawnLocationMarkerColor 0
#define INS_REV_DEF_respawnLocationMarkerType 0
#define INS_REV_DEF_destroyDamagedVehicle 0
#define INS_REV_DEF_destroyDamagedVehicleDelay 30
#define INS_REV_DEF_jip_action 1
#define INS_REV_DEF_can_drag_body 1
#define INS_REV_DEF_can_carry_body 1
#define INS_REV_DEF_medevac 1
#define INS_REV_DEF_can_respawn_player_body 0
#define INS_REV_DEF_half_dead_repsawn_player_body 1
#define INS_REV_DEF_near_friendly 0
#define INS_REV_DEF_near_friendly_distance 50
#define INS_REV_DEF_near_enemy 0
#define INS_REV_DEF_near_enemy_distance 50
#define INS_REV_DEF_all_dead_respawn 1
#define INS_REV_DEF_loadout_on_respawn 0