#define INS_DEF_numCaches 8
#define INS_DEF_intelItems 3
#define INS_DEF_probOfDrop 10
#define INS_DEF_intelTimeout 120
#define CAS_DEF_casPlayerTimeout 30
#define CAS_DEF_casPlayerTimeLimit 90
#define CAS_DEF_casAITimeout 60
#define CAS_DEF_casNumRequestsBLUFOR 2
#define CAS_DEF_casNumRequestsOPFOR 1